// GENERATED BY grunt make_dir_module.
"use strict";
var wash$exe$cat$$ = require("wash/exe/cat"), wash$exe$clear$$ = require("wash/exe/clear"), wash$exe$cp$$ = require("wash/exe/cp"), wash$exe$echo$$ = require("wash/exe/echo"), wash$exe$ls$$ = require("wash/exe/ls"), wash$exe$mkdir$$ = require("wash/exe/mkdir"), wash$exe$pwd$$ = require("wash/exe/pwd"), wash$exe$readline$$ = require("wash/exe/readline"), wash$exe$rm$$ = require("wash/exe/rm"), wash$exe$wash$$ = require("wash/exe/wash");
var dir = {};
exports["default"] = dir;
dir["cat"] = wash$exe$cat$$.default;
dir["clear"] = wash$exe$clear$$.default;
dir["cp"] = wash$exe$cp$$.default;
dir["echo"] = wash$exe$echo$$.default;
dir["ls"] = wash$exe$ls$$.default;
dir["mkdir"] = wash$exe$mkdir$$.default;
dir["pwd"] = wash$exe$pwd$$.default;
dir["readline"] = wash$exe$readline$$.default;
dir["rm"] = wash$exe$rm$$.default;
dir["wash"] = wash$exe$wash$$.default;
exports.dir = dir;

//# sourceMappingURL=exe_modules.js.map