// GENERATED BY grunt make_dir_module.
define(
  "wash/exe_modules",
  ["wash/exe/cat", "wash/exe/clear", "wash/exe/cp", "wash/exe/echo", "wash/exe/ls", "wash/exe/mkdir", "wash/exe/pwd", "wash/exe/readline", "wash/exe/rm", "wash/exe/wash", "exports"],
  function(
    wash$exe$cat$$,
    wash$exe$clear$$,
    wash$exe$cp$$,
    wash$exe$echo$$,
    wash$exe$ls$$,
    wash$exe$mkdir$$,
    wash$exe$pwd$$,
    wash$exe$readline$$,
    wash$exe$rm$$,
    wash$exe$wash$$,
    __exports__) {
    "use strict";

    function __es6_export__(name, value) {
      __exports__[name] = value;
    }

    var m0;
    m0 = wash$exe$cat$$["default"];
    var m1;
    m1 = wash$exe$clear$$["default"];
    var m2;
    m2 = wash$exe$cp$$["default"];
    var m3;
    m3 = wash$exe$echo$$["default"];
    var m4;
    m4 = wash$exe$ls$$["default"];
    var m5;
    m5 = wash$exe$mkdir$$["default"];
    var m6;
    m6 = wash$exe$pwd$$["default"];
    var m7;
    m7 = wash$exe$readline$$["default"];
    var m8;
    m8 = wash$exe$rm$$["default"];
    var m9;
    m9 = wash$exe$wash$$["default"];
    var dir = {};
    __es6_export__("dir", dir);
    __es6_export__("default", dir);
    dir["cat"] = m0;
    dir["clear"] = m1;
    dir["cp"] = m2;
    dir["echo"] = m3;
    dir["ls"] = m4;
    dir["mkdir"] = m5;
    dir["pwd"] = m6;
    dir["readline"] = m7;
    dir["rm"] = m8;
    dir["wash"] = m9;
  }
);

//# sourceMappingURL=exe_modules.js.map